"""Add user_roles table

Revision ID: 3ad357244766
Revises: 201943988b17
Create Date: 2026-02-05 18:13:49.128861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad357244766'
down_revision = '201943988b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.UUID(), nullable=False))
        batch_op.create_unique_constraint('uq_user_role', ['user_id', 'role_id'])
        batch_op.drop_constraint(batch_op.f('user_roles_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_roles_role_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_roles_role_id_fkey'), 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_roles_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_constraint('uq_user_role', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
