"""Add year to leave_ledger

Revision ID: 4c91afea7840
Revises: 642651f39d7a
Create Date: 2026-02-09 10:42:32.726119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c91afea7840'
down_revision = '642651f39d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_quota', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('used_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remaining_days', sa.Integer(), nullable=False))
        batch_op.alter_column('leave_type_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['user_id', 'leave_type_id', 'year'])
        batch_op.drop_column('action')
        batch_op.drop_column('reason')
        batch_op.drop_column('change_amount')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('leave_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('change_amount', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('leave_type_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('remaining_days')
        batch_op.drop_column('used_days')
        batch_op.drop_column('total_quota')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
