"""Add year and balances to leave ledger

Revision ID: 53ecad0aab3e
Revises: 4c91afea7840
Create Date: 2026-02-09 10:59:05.238070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ecad0aab3e'
down_revision = '4c91afea7840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_ledger', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('leave_ledger_user_id_leave_type_id_year_key'), type_='unique')
        batch_op.create_unique_constraint('uq_user_leave_year', ['user_id', 'leave_type_id', 'year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_ledger', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_leave_year', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('leave_ledger_user_id_leave_type_id_year_key'), ['user_id', 'leave_type_id', 'year'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
