"""Add password hash to users

Revision ID: 58db3fe0da82
Revises: 3ad357244766
Create Date: 2026-02-06 09:55:18.457403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58db3fe0da82'
down_revision = '3ad357244766'
branch_labels = None
depends_on = None


def upgrade():
    # 1️Add column as NULLABLE first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('password_hash', sa.String(length=255), nullable=True)
        )

    # 2️Backfill existing rows
    from werkzeug.security import generate_password_hash
    op.execute(
        "UPDATE users SET password_hash = '{}'".format(
            generate_password_hash("password123")
        )
    )

    # 3️Enforce NOT NULL constraint
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'password_hash',
            nullable=False
        )




    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    op.create_table('leave_types',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_types_pkey'))
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('leave_type_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('leave_requests_leave_type_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('leave_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_requests_pkey'))
    )
    op.create_table('leave_ledger',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('leave_type_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('change_amount', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('leave_ledger_leave_type_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('leave_ledger_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_ledger_pkey'))
    )
    # ### end Alembic commands ###
