"""Add total_days to leave_requests

Revision ID: 642651f39d7a
Revises: 58db3fe0da82
Create Date: 2026-02-06 16:41:35.801683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '642651f39d7a'
down_revision = '58db3fe0da82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('applied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('leave_type_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
       batch_op.add_column(
              sa.Column('yearly_quota', sa.Integer(), nullable=False, server_default="0")
       )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('yearly_quota')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.alter_column('reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('leave_type_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('applied_at')
        batch_op.drop_column('total_days')

    # ### end Alembic commands ###
