"""Add rejection_reason to leave_requests

Revision ID: 7be40227825d
Revises: ae71527e8054
Create Date: 2026-02-19 12:32:23.009471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be40227825d'
down_revision = 'ae71527e8054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('processed_at')
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
