"""add is_active to leave_types

Revision ID: ae71527e8054
Revises: 53ecad0aab3e
Create Date: 2026-02-13 12:11:24.412926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae71527e8054'
down_revision = '53ecad0aab3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_ledger', schema=None) as batch_op:
        batch_op.drop_column('remaining_days')

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('leave_types_name_key'), type_='unique')
        batch_op.drop_column('yearly_quota')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yearly_quota', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('leave_types_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('leave_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_days', sa.INTEGER(), autoincrement=False, nullable=False))

    op.drop_table('leaves')
    # ### end Alembic commands ###
